language: go
sudo: required
go:
  - 1.5.2

env:
    matrix:
       - GIMME_OS=windows GIMME_ARCH=amd64
       - GIMME_OS=linux GIMME_ARCH=amd64
       - GIMME_OS=linux GIMME_ARCH=386
       - GIMME_OS=darwin GIMME_ARCH=amd64

after_script:
- ls -l ../../../../bin

# Workaround for travis-ci/gimme#25 to pick up latest version of gimme and run again
before_install:
  - curl -o gimme -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
  - chmod u+x gimme
  - unset GOROOT GOTOOLDIR
  - eval "$(./gimme 1.5)"
  - go version
  - go env

# Part of the same workaround.
before_script:
  - go get -d -v ./...

# Part of the same workaround.
script:
  - go build -v ./...
