language: go
sudo: required
go:
- 1.5.2
env:
  matrix:
  - GIMME_OS=windows GIMME_ARCH=amd64
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=linux GIMME_ARCH=386
  - GIMME_OS=darwin GIMME_ARCH=amd64
  global:
  - GO15VENDOREXPERIMENT=1
  - secure: w0dxoP+OLUFv4h5+g6qY41jUuzWB0rB2/vFAVkSOGX4OX7zuhDnZeL+Vr7I7CwNlWs5y2km9iMZsjv+5K4VuB15eiWOxYT4CCIcfjIET7pAnCnq6lbu+ZESaIpBMmcPu9gCbRNNT5rvfm2NfzWeZeyyH1Avs9qtt3/Op/BZRvv8bEJ5sZpalkG4IPrR/Cy7FlV3oHKMVeEzW1oQhV46ON7F53EB6VZdkgMIzldYSV9Y6ICf4z6sN8I9uBasXM3psPbqNGJfl4xNwNrfStuh9cNXLSBg9hq0UVzaTbNn8BLEQM2zucvV15YKYw45SzUQK7KoPYPFkmvgE4y7R2cfDnZzj2zypz9pz2IWumrsNi4B8N/qvInZGOBR6htDT8SM+KRoTF5k4MVV/iE6oxXZ7nRLNQQeAH9UIFNs9ECxuO7tAiteCntojbk/8qw6Pr+1+Gv3B0B9e5uZ00MlJEkjlHxzsfn9RJ87fUH4wUCsHWfQolyrGx5XI8lSHwJ+6EOJyHPBbVte9/NVIQtBfJ4qooB/rEjrG9mtNM+riFugF/1Z9ImIbvMEOH8FHwoC4fmW44eAwG7wUNCsogbDG+ZmoZKiyetRT0o8h0VHYRgXkvOk1jVKc1/FOpHoWbXy8tOqGjhLpumj0UrcOPkgx1+dDyv88uKX06McfVQeTNLzJwQ4=
after_script:
- ls -l ../../../../bin
before_install:
- cd $HOME/gopath/src/github.com
- mv -f JFrogDev jfrogdev
- cd $HOME/gopath/src/github.com/jfrogdev/jfrog-cli-go
- curl -o gimme -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
- chmod u+x gimme
- unset GOROOT GOTOOLDIR
- eval "$(./gimme 1.5)"
- go version
- go env
before_script:
- go get -d -v ./...
script:
- go build -v ./...
deploy:
  skip_cleanup: true
  file: bintray_descriptors/${GIMME_OS}_${GIMME_ARCH}.json
  provider: bintray
  key: "$API_KEY"
  user: eyalbr
