build: off

environment:
  GOPATH: c:\gopath
  JFROG_CLI_RT_URL:
    secure: KkjTm9RrjPrzDQocmxTmQPdE2bozPgix5CFjkeam6Fscx1S34tR4Hpqg3j/7R+AH
  JFROG_CLI_RT_USER:
    secure: b79qvuMVVlqhdsKoJC046g==
  JFROG_CLI_RT_PASSWORD:
    secure: eebX+bKmzB9hHtjniAvmXQYLqNSWPxPwy71sOeNLrkU=

clone_folder: c:\gopath\src\github.com\jfrog\jfrog-cli-go

stack: go 1.10

test_script:
- go vet github.com\jfrog\jfrog-cli-go\jfrog-cli\jfrog
- go test -v github.com\jfrog\jfrog-cli-go\jfrog-cli\jfrog --rt.url="$JFROG_CLI_RT_URL" --rt.user="$JFROG_CLI_RT_USER" --rt.password="$JFROG_CLI_RT_PASSWORD"
