build: off

branches:
  only:
  - master

environment:
  GOPATH: c:\gopath

clone_folder: c:\gopath\src\github.com\jfrog\$project

stack: go 1.10

#before_test:
#- go vet github.com\jfrog\jfrog-cli-go\jfrog-cli\jfrog
#
#test_script:
#- go test -v github.com\jfrog\jfrog-cli-go\jfrog-cli\jfrog --rt.url=JFROG_CLI_RT_URL --rt.user=JFROG_CLI_RT_USER --rt.password=JFROG_CLI_RT_PASSWORD
