# ~~~ How to use Appveyor ~~~
# Preconditions: JFrog Platform instance
#
# = Trigger tests on commits =
#   1. Create a new project in Appveyor and choose jfrog-cli-go.
#   2. In project settings, copy the 'Webhook URL' and create a new 'Push events' Webhook in Github.
#
# = Configure Artifactory =
#   1. Create all necessary repositories for tests according to the README.
#   2. Create a remote Nuget repository in Artifactory:
#     A. Repository Key: choco
#     B. Url: https://chocolatey.org
#     * The test uses Chocolatey package manager to download Gradle Nuget package through Artifactory's cache.
#
# = Override credentials in Appveyor in case of a fork =
#   1. In the project at Appveyor - Go to settings -> Environment.
#   2. Override 'JFROG_CLI_RT_URL' and 'JFROG_CLI_RT_USER'
#   3. Override 'JFROG_CLI_RT_PASSWORD' with variable encryption.

image:
  - Visual Studio 2019

build: off
skip_tags: true
stack: go 1.14, node 15, jdk 8
clone_folder: c:\gopath\src\github.com\jfrog\jfrog-cli
environment:
  GOPATH: c:\gopath
  # Added in order to prevent fetching the outdated dependencies versions from go cache.
  GOPROXY: direct
  GO111MODULE: on
  CGO_ENABLED: 0
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  # .NET CLI version
  CLI_VERSION: Latest

  JFROG_CLI_RT_URL:
    secure: RIh0gGFDn2JAnLUEEqLsQm0ihToJ6/4LiR411QpvqDgYYE7Y4Eif2e+wYndvHXnW
  JFROG_CLI_RT_USER:
    secure: YEB5Wiv9a2vNpUhy+MfL+A==
  JFROG_CLI_RT_PASSWORD:
    secure: Um8o75MQIieSavIemF4ySA==
  JFROG_CLI_DIST_URL:
    secure: RIh0gGFDn2JAnLUEEqLsQrfLmtDrzDd5Qphea4gOE0Lu1Uz2Xa/y+D0Mld917gwy
  JFROG_CLI_ACCESS_TOKEN:
    secure: sStoT/GxZjEl/toWXau6wanS9NdCTsTxApUZCE7TTt4Wp4lVUwg1OqzdwWNic4R9YnAu90VY+5F/vI7I6Ijl1V/GcSCFLSVEr03rJj7OfzRkt5+obiNNotiBR9cP7bKQrCCAf2044fOukKPrjvZW7cV2tFoBQP8TmetaVmogBk52BMNcC44+MsLmh060htRFVHnigloE73U+TE3w1pgDd5QMM+z8sj+UGLGOj8W8KHprfYUS/JfUUuYWQYLAJIRvyGMxci5KIn6VygQzHagJ6rAUUFmZgxaWyJ5yRGufgteKTreIiwU0nk/iqTYPWgZJzagsfgrVWz0mkZG7d+Yjqw13N0qhCYRzRcyc4md4jBb4zrTUIcIdI+Ot0khhmFx1rq7sutWyqeCshN3bPk4vZ4AROczLJg8v91+2+keXzI3z/0LqswNqj0v1+15D+FHF86rxToun2HK765INHgCOMjhMxz4hOSWsz/IK0jhLxNX7S5geW/5+1UPh+FPZq4MLfwi1HWltg3Pi9PLdGacLmpxCAL/1MaqtI5Du2BxjuiSWPnOjAfsvScqoj6lyT8Sk3pwUGVPY8AK/Bu7vyQbB80v1yFind5+Rqvt8wPTPL72CPmjIMl8w4qrb1nEheOj8JQO1s701qF9xbKcOr9HXaaLpHuakw4sfha7jFhhgY1q+EQ06WbPHYl3DxEglDlioX/xHURRfSq39tpF6Auwl1GoiKNAsRLcQn+zi7fuf4VuM63zZuH+oWgJxwqm4CYkSb/MXErqvxjRVjD/L2Tn6d1TeSo9s4hyfb8T/gyyT2lVmQX5WqaDejcXFL1bEJNvQ15pkJfMRZlZlmtVCyC98YJ1QPf3NRmEyIXmH0S+kFCzcphbID1gI47vNJtRv0Wnaabo0uAV6bky/7o9KsWib0g==
  JFROG_CLI_ACCESS_URL:
    secure: RIh0gGFDn2JAnLUEEqLsQph5j1FANSk/QUtRJvh8kSfFYyaZd4ONAf1aP/WV9BOA

  COMMON_TESTS_ARGS:
    go test -v github.com\jfrog\jfrog-cli --timeout 0 --rt.url="%JFROG_CLI_RT_URL%" --rt.user="%JFROG_CLI_RT_USER%" --rt.password="%JFROG_CLI_RT_PASSWORD%" --access.url="%JFROG_CLI_ACCESS_URL%" --access.accessToken="%JFROG_CLI_ACCESS_TOKEN%"

  matrix:
    - VET:
      TEST_SUIT:
        go vet github.com\jfrog\jfrog-cli &&
        .\\build\\build.bat &&
        .\\jfrog.exe --version
    - ARTIFACTORY_TESTS:
      TEST_SUIT:
        "%COMMON_TESTS_ARGS%  --test.artifactory=true"
    - NPM_TESTS:
      TEST_SUIT:
        "%COMMON_TESTS_ARGS% --test.npm=true"
    - MAVEN_TESTS:
      TEST_SUIT:
        "%COMMON_TESTS_ARGS% --test.maven=true"
    - GRADLE_TESTS:
    TEST_SUIT:
      "choco install gradle -s %JFROG_CLI_RT_URL%/api/nuget/choco -u %JFROG_CLI_RT_USER% -p %JFROG_CLI_RT_PASSWORD% &&
      %COMMON_TESTS_ARGS% --test.gradle=true"
  - NUGET_TESTS:
    TEST_SUIT:
      "%COMMON_TESTS_ARGS% --test.nuget=true"
  - GO_TESTS:
    TEST_SUIT:
      "%COMMON_TESTS_ARGS% --test.go=true"
  - PIP_TESTS:
    TEST_SUIT:
      "C:\\Python37-x64\\python -m venv pip-venv &&
      %COMMON_TESTS_ARGS% --test.pip=true --rt.pipVirtualEnv=C:\\gopath\\src\\github.com\\jfrog\\jfrog-cli\\pip-venv\\Scripts"
  - DISTRIBUTION_TESTS:
    TEST_SUIT:
      "%COMMON_TESTS_ARGS% --rt.distUrl=%JFROG_CLI_DIST_URL% --test.distribution=true"
  - PLUGINS_TESTS:
    TEST_SUIT:
      "%COMMON_TESTS_ARGS% --test.plugins=true"

install:
  - ps: Install-Product node 15

test_script:
  - "%TEST_SUIT%"
