build: off

branches:
  only:
  - dev

environment:
  GOPATH: c:\gopath

clone_folder: c:\gopath\src\github.com\jfrog\$project

stack: go 1.10

test_script:
- go vet github.com\jfrog\jfrog-cli-go\jfrog-cli\jfrog
- go test -v github.com\jfrog\jfrog-cli-go\jfrog-cli\jfrog --rt.url=JFROG_CLI_RT_URL --rt.user=JFROG_CLI_RT_USER --rt.password=JFROG_CLI_RT_PASSWORD
