image:
- Visual Studio 2017

build: off

stack: go 1.10, node 8, jdk 8
environment:
  GOPATH: c:\gopath
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

  RT_CREDENTIALS:
  JFROG_CLI_RT_URL:
    secure: KkjTm9RrjPrzDQocmxTmQPdE2bozPgix5CFjkeam6Fscx1S34tR4Hpqg3j/7R+AH
  JFROG_CLI_RT_USER:
    secure: b79qvuMVVlqhdsKoJC046g==
  JFROG_CLI_RT_PASSWORD:
    secure: eebX+bKmzB9hHtjniAvmXQYLqNSWPxPwy71sOeNLrkU=
  JFROG_CLI_BINTRAY_USER:
    secure: 79qvuMVVlqhdsKoJC046g==
  JFROG_CLI_BINTRAY_APIKEY:
    secure: OHRW/mJst4W1Dgnh+fI0IAIerXVCR6TMb6oG9ug0HYsMPmgSIISiEIKiFv1HcWK5

clone_folder: c:\gopath\src\github.com\jfrog\jfrog-cli-go

before_test:
  - choco install gradle

test_script:
#  - go vet github.com\jfrog\jfrog-cli-go\jfrog-cli\jfrog
#  - go test -v github.com\jfrog\jfrog-cli-go\jfrog-cli\jfrog
#    --rt.url="%JFROG_CLI_RT_URL%" --rt.user="%JFROG_CLI_RT_USER%" --rt.password="%JFROG_CLI_RT_PASSWORD%"
#    --timeout 0 --test.maskCredentials

  - go test -v github.com\jfrog\jfrog-cli-go\jfrog-cli\jfrog
    --rt.url="%JFROG_CLI_RT_URL%" --rt.user="%JFROG_CLI_RT_USER%" --rt.password="%JFROG_CLI_RT_PASSWORD%"
    --bt.user="%JFROG_CLI_BINTRAY_USER%" --bt.key="%JFROG_CLI_BINTRAY_APIKEY%"
    --test.artifactory=false --test.bintray=true
    --timeout 0

  - go test -v github.com\jfrog\jfrog-cli-go\jfrog-cli\jfrog
    --rt.url="%JFROG_CLI_RT_URL%" --rt.user="%JFROG_CLI_RT_USER%" --rt.password="%JFROG_CLI_RT_PASSWORD%"
    --test.artifactory=false --test.buildTools=true
    --timeout 0 --test.maskCredentials