resources:
- name: sverdlov93_jfrog_cli_gitResource
  type: GitRepo
  configuration:
    path: sverdlov93/jfrog-cli
    gitProvider: github_sverdlov93_jfrog_cli_integration
    buildOn:
      pullRequestCreate: true
    branches:
      include: dev
- name: sverdlov93_jfrog_cli_buildInfoResource
  type: BuildInfo
  configuration:
    sourceArtifactory: rt_sverdlov93_jfrog_cli_integration
    buildName: jfrog-cli-dev
    buildNumber: $run_number
pipelines:
- name: sverdlov93_jfrog_cli_pipeline
  configuration:
    environmentVariables:
      readOnly:
        CI: "true"
        JFROG_CLI_BUILD_NAME: jfrog-cli-dev
        JFROG_CLI_BUILD_NUMBER: $run_number
        JFROG_CLI_BUILD_URL: $step_url
  steps:
  - name: NpmBuildStep
    type: Bash
    configuration:
      environmentVariables:
        JFROG_BUILD_STATUS: PASS
      integrations:
      - name: rt_sverdlov93_jfrog_cli_integration
      inputResources:
      - name: sverdlov93_jfrog_cli_gitResource
    execution:
      onExecute:
      - cd $res_sverdlov93_jfrog_cli_gitResource_resourcePath
      - jfrog rt c sverdlov93_jfrog_cli_serverId --url $int_rt_sverdlov93_jfrog_cli_integration_url
        --user $int_rt_sverdlov93_jfrog_cli_integration_user --enc-password=false
      - jfrog rt npm-config --server-id-resolve sverdlov93_jfrog_cli_serverId --repo-resolve
        npm-virtual
      - jfrog rt npmi
      - jfrog rt bag
      - jfrog rt bce
      onComplete:
      - add_run_files /tmp/jfrog/. jfrog
      onFailure:
      - export JFROG_BUILD_STATUS=FAIL
      - jfrog rt bce
      - jfrog rt bp
  - name: PublishBuildInfoStep
    type: PublishBuildInfo
    configuration:
      inputResources:
      - name: sverdlov93_jfrog_cli_gitResource
      outputResources:
      - name: sverdlov93_jfrog_cli_buildInfoResource
      inputSteps:
      - name: NpmBuildStep
      forceXrayScan: true
    execution:
      onComplete:
      - update_commit_status sverdlov93_jfrog_cli_gitResource
