name: Print Job Summary
on:
  push:
    branches:
      - '**'
jobs:
  insert-to-summary-file:
    runs-on: self-hosted
    steps:
#      Removed for self hosted, there is no need to setup go
#      - name: Setup Go
#        uses: actions/setup-go@v5
#        with:
#          go-version: 1.20.x
#          cache: false
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build current CLI
        run: go build .

      - name: Run CLI Ping
        run: ./jfrog-cli rt ping --url="https://ecosysjfrog.jfrog.io/artifactory" --access-token=${{ secrets.PLATFORM_ADMIN_TOKEN }}

#      - name: Adding markdown
#        run: echo '### Hello world! 🚀' >> $GITHUB_STEP_SUMMARY

#      - name: copy content of the file
#        run: cat markdown.txt >> $GITHUB_STEP_SUMMARY