name: Print Job Summary
on:
  push:
    branches:
      - '**'
env:
  JFROG_CLI_LOG_LEVEL: DEBUG
jobs:
  Upload-Files-And-Check-Summary:
    runs-on: self-hosted
    steps:
#      - name: Setup Go
#        uses: actions/setup-go@v5
#        with:
#          go-version: 1.20.x
#          cache: false
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build current CLI
        run: go build .

      - name: Run dry run upload
        run: ./jfrog-cli rt upload --spec=./testdata/filespecs/upload_dev_spec_b.json --dry-run --url="https://ecosysjfrog.jfrog.io/artifactory" --access-token=${{ secrets.PLATFORM_ADMIN_TOKEN }}

      - name: Run dry run upload2
        run: ./jfrog-cli rt upload --spec=./testdata/filespecs/upload_dev_spec_b.json --dry-run --url="https://ecosysjfrog.jfrog.io/artifactory" --access-token=${{ secrets.PLATFORM_ADMIN_TOKEN }}
