name: Print Job Summary
on:
  push:
    branches:
      - '**'
jobs:
  insert-to-summary-file:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY

