name: Maven Tests
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  # Triggers the workflow on labeled PRs only.
  pull_request_target:
    types: [ labeled ]
# Ensures that only the latest commit is running for each PR at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  Maven-Tests:
    if: contains(github.event.pull_request.labels.*.name, 'safe to test') || github.event_name == 'push'
    name: Maven tests (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, windows, macos ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: ./.github/common-steps/install-go-with-cache

      - name: Setup Maven v3.8.8 for macOS
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.8
        if: runner.os == 'macOS'

      - uses: ./.github/common-steps/install-local-artifactory
        with:
          RTLIC: ${{ secrets.RTLIC }}

      - name: Run Maven tests
        run: go test -v github.com/jfrog/jfrog-cli --timeout 0 --test.maven
