name: Sign Dawrin Binaries for Release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
        default: '0.0.0'
      binaryFileName:
        description: 'Binary file name'
        required: true
        default: 'jf'
env:
    binaryFileName: ${{ github.event.inputs.binaryFileName }}
    releaseVersion: ${{ github.event.inputs.releaseVersion }}
jobs:
  # Builds, signs, notarize and uploads the macOS binaries
  prepareBinary:
    name: Prepare-Binary
    runs-on: macos-latest
    strategy:
      matrix:
        goarch: [ arm64,amd64 ]
    steps:
      # Setup
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          cache: false

      # Build
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Build
        run: ./build/build.sh ${{ env.binaryFileName }}

      - name: Sign & Notarize
        env:
          APPLE_CERT_DATA: ${{ secrets.APPLE_CERT_DATA }}
          APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_ACCOUNT_ID: ${{ secrets.APPLE_ACCOUNT_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          BINARY_FILE_NAME: ${{ env.binaryFileName }}
          APP_TEMPLATE_PATH: ./build/appleBundles/${{ env.binaryFileName }}.app
        run: ./build/darwin-sign-and-notarize.sh

      # Upload
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.binaryFileName }}-darwin-v${{ env.releaseVersion }}-${{ matrix.goarch }}
          path: ./build/${{ env.binaryFileName }}.app/Contents/MacOS/${{ env.binaryFileName }}
          retention-days: 1
          if-no-files-found: error


