name: Sign Dawrin Binaries for Release
on:
  workflow_dispatch:
env:
    binaryFileName: ${{ github.event.inputs.releaseVersion }}
    releaseVersion: ${{ github.event.inputs.releaseVersion }}
jobs:
  # Builds, signs, notarize and uploads the macOS binaries
  prepareBinary:
    name: Prepare-Binary
    runs-on: macos-latest
    strategy:
      matrix:
        goarch: [ arm64,amd64 ]
    steps:
      # Setup
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          cache: false

      # Build
      - name: Checkout Source
        uses: actions/checkout@v4
# TODO uncomment this after tests
#        with:
#          ref: v2
      - name: Build
        run: ./build/build.sh

      - name: Sign & Notarize
        env:
          APPLE_CERT_DATA: ${{ secrets.APPLE_CERT_DATA }}
          APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_ACCOUNT_ID: ${{ secrets.APPLE_ACCOUNT_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          BINARY_FILE_NAME: ${{ env.binaryFileName }}
          APP_TEMPLATE_PATH: ./build/jf.app
        run: ./build/darwin-sign-and-notarize.sh

      # Upload
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.binaryFileName }}-darwin-v${{ env.releaseVersion }}-${{ matrix.goarch }}
          path: ./build/jf.app/Contents/MacOS/${{ env.binaryFileName }}
          retention-days: 1


