name: Scripts Tests
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
# Ensures that only the latest commit is running for each PR at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  Scripts-tests:
    name: Script tests (${{ matrix.os }})
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, windows, macos ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Test install CLI - jf
        run: sh build/installcli/jf.sh && jf --version

      - name: Test install CLI - jfrog
        run: sh build/installcli/jfrog.sh && jfrog --version

      - name: Test get CLI - jf
        run: sh build/getcli/jf.sh && ./jf --version

      - name: Test get CLI - jfrog
        run: sh build/getcli/jfrog.sh && ./jfrog --version

      - name: Test Build CLI - sh
        run: sh build/build.sh && ./jf --version
        if: ${{ matrix.os != 'windows' }}

      - name: Test Build CLI - bat
        run: build/build.bat && ./jf.exe --version
        if: ${{ matrix.os == 'windows' }}

      - name: Test install npm - v2
        run: npm install
        working-directory: build/npm/v2

      - name: Test install npm - v2-jf
        run: cd build/npm/v2-jf && npm install
