name: Sign MacOS Binaries
on: [push]
jobs:
  SignBinary:
    name: Sign-JFrog-CLI-MacOS-Binary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-arm64]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          cache: false

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Build
        run: go build -v .

      - name: Sign Binary
        env:
          APPLE_CERT_DATA: ${{ secrets.APPLE_CERT_DATA }}
          APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: ./build/macOsSign/signMacOsBinary.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jfrog-cli-${{ matrix.os }}
          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: ./jfrog-cli
          retention-days: 1
