name: Sign MacOS Binaries
on: [push]
jobs:
  # Verify a commit message and extract the upgraded version number.
  is_version_upgrade:
    runs-on: ubuntu-latest
    outputs:
      match: ${{ steps.regex.outputs.match }}
      version: ${{ steps.regex.outputs.version }}
    steps:
      - id: regex
        uses: actions/github-script@v7
        with:
          script: |
            const message = context.payload.head_commit.message;
            console.log('Commit message:', message);
            const regex = /^Bump version from \d+\.\d+\.\d+ to (\d+\.\d+\.\d+)$/;
            const regexMatch = message.match(regex);
            console.log('Match:', regexMatch);
            if (regexMatch) {
              return { match: true, version: match[1] };
            } else {
              return { match: false, version: '' };
            }
  # Sign the JFrog CLI binary for macOS
  SignBinary:
    needs: is_version_upgrade
    if: ${{needs.is_version_upgrade.outputs.match  == 'true' }}
    name: Sign-JFrog-CLI-MacOS-Binary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-14-large]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          cache: false

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Build
        run: ./build/build.sh

      - name: Sign Binary
        env:
          APPLE_CERT_DATA: ${{ secrets.APPLE_CERT_DATA }}
          APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: ./build/macOsSign/signMacOsBinary.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jf-${{ matrix.os }}-${{ needs.check_commit.outputs.version }}
          path: ./jf
          retention-days: 1
