name: Sign Binaries

on: [push]
jobs:
  SignMacOs:
    name: SignBinary
    runs-on: macos-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          cache: false

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Build
        run: go build -v .

      - name: Sign Binary
        env:
          APPLE_CERT_DATA: ${{ secrets.APPLE_CERT_DATA }}
          APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: ./signscript.sh