name: JFrog CLI Tests
on:
  push:
    branches:
      - v2
      - v1
      - dev
      - dev-v1
    # Triggers the workflow on labeled PR only.
  pull_request_target:
    types: [labeled]
jobs:
  CLI-Tests:
    name: ${{ matrix.product }} ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        product: [artifactory, pip, distribution, xray, plugins, npm, maven, gradle, nuget, go]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Install npm
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      if: ${{ matrix.product == 'npm' }}

    - name: Install Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
      if: ${{ matrix.product == 'maven' || matrix.product == 'gradle' }}

    - name: Install NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 5.x
      if: ${{ matrix.product == 'nuget' }}

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
      if: ${{ matrix.product == 'pip' }}

    - name: Setup Python virtual environment
      if: ${{ matrix.product == 'pip' }}
      run: python -m venv venv

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Prerequisite-windows-Tests
      if: ${{ matrix.product == 'pip' && matrix.product == 'windows-latest' }}
      run: . venv\Scripts\activate.ps1

    - name: Prerequisite-ubuntu-Tests
      if: ${{ matrix.product == 'pip' && matrix.product == 'ubuntu-latest' }}
      run: source venv/bin/activate

    - name: Prerequisite-macos-Tests
      if: ${{ matrix.product == 'pip' && matrix.product == 'macos-latest' }}
      run: source venv/bin/activate

    - name: CLI-Tests
      run: go test -v github.com/jfrog/jfrog-cli --timeout 0 --test.${{ matrix.product }}=true --jfrog.url=${{ secrets.PLATFORM_URL }} --jfrog.adminToken=${{ secrets.PLATFORM_ADMIN_TOKEN }} --jfrog.user=${{ secrets.PLATFORM_USER }} --rt.dockerRepoDomain=ecosysjfrog-docker-virtual.jfrog.io --rt.dockerVirtualRepo=docker-virtual --rt.DockerLocalRepo=docker-local --rt.dockerRemoteRepo=docker-remote --ci.runId=${{ github.run_number }}${{ matrix.product }}${{ matrix.os }}

  Docker-Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Docker-Tests
      run: go test -v -timeout 0 --test.docker=true --jfrog.url=${{ secrets.PLATFORM_URL }} --jfrog.adminToken=${{ secrets.PLATFORM_ADMIN_TOKEN }} --rt.dockerRepoDomain=ecosysjfrog-docker-virtual.jfrog.io --rt.dockerVirtualRepo=docker-virtual --rt.DockerLocalRepo=docker-local --rt.dockerRemoteRepo=docker-remote --ci.runId=${{ github.run_number }}${{ matrix.product }}${{ matrix.os }}