name: JFrog CLI Github Examples
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: amd64/golang:latest
    steps:
      - name: setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
      - run: jfrog --version
        env:
          JF_ARTIFACTORY_JF_RT: $({ secrets.JF_RT })
      - name: Checkout 
        uses: actions/checkout@v1
      - name: Build
        run: |
          # Build the code
          jfrog go-config --server-id-resolve art --repo-resolve go
          export CGO_ENABLED=0
          #recording all the build dependecies that are being created by this build
          jfrog go build -o jfrog -ldflags '-w -extldflags "-static"' main.go --module "JFrog CLI Example"
          # Get the version
          version=$(./jfrog -v | cut -d "" -f 3)
          echo Build JFrog CLI version $version
          #Upload the jfrog-cli binary
          #This command will upload the binaries as artifacts to Artifactory (and will be used by both - artifactory and xray, to scan the builds)
          jfrog rt u jfrog rc-local/jfrog-cli-releases/$version/
          #Add env vars
          #build info creation 
          jfrog rt bce
          #Add git info
          jfrog rt bag --config issues.yml
          #Publish build-info
          jfrog rt bs
          # Promote build to staging
          jfrog rt bpr staging-local

